### ISSUE TITLE
Laden ontladen overzicht per kWh en Euro

### ISSUE THREAD

**Issue by sideriusj** [PimDoos/ha-sessy#110]
Laden ontladen overzicht per dag maand jaar in kWh en Euro.

Zodat je weet of je winst / verlies hebt met je sessy(s).

**Comment by PimDoos** [comment]
Deze integratie focust op het koppelen van data uit Sessy naar Home Assistant. Specifiek rendement in euro's verschilt per situatie. Hiervoor zou je een Template sensor kunnen maken die het vermogen van je Sessy (W) vermenigvuldigd met de huidige stroomprijs (€/kWh), wat een sensor in €/h oplevert. Met een Riemann Sum helper kun je hier harde euro's van maken.
Laden en ontladen per dag/maand/jaar kun je al zien op basis van de statistieken van de Charged/Discharged Energy sensor. Dit is inzichtelijk via een statistics-graph card.

Bijvoorbeeld voor de hoeveelheid geladen energie vandaag:
```yaml
chart_type: bar
title: Charged today
period: hour
type: statistics-graph
entities:
  - sensor.sessy_dxxx_charged_energy
stat_types:
  - change
days_to_show: 1
```
