### ISSUE TITLE
Add Energy sensors

### ISSUE THREAD

**Issue by PimDoos** [PimDoos/ha-sessy#8]
Add energy sensors (kWh meters)
- Battery Charged
- Battery Discharged

Renewable Energy meters:
- Phase # Energy Consumed
- Phase # Energy Produced

**Comment by PimDoos** [comment]
Awaiting API change from Sessy.

**Comment by PimDoos** [comment]
Temporary workaround to get Energy Dashboard working:
Add these template sensors via yaml:
```yaml
template:
  - sensor:
    - name: Sessy Power Charging
      state: >
        {% set power = states("sensor.sessy_xxxx_power") | int %}
        {{ (power,0) | min *-1 }}
      state_class: measurement
      device_class: power
      unit_of_measurement: W
      
    - name: Sessy Power Discharging
      state: >
        {% set power = states("sensor.sessy_xxxx_power") | int %}
        {{ (power,0) | max }}
      state_class: measurement
      device_class: power
      unit_of_measurement: W
```

Then add two helpers for these template sensors:
![image](https://user-images.githubusercontent.com/17709721/226434320-68690d4c-9c4d-436d-aaf8-1029ce440f41.png)

**Comment by TomNagel123** [comment]
The power that is reported by the Sessy is very inaccurate. 
I have seen that 
- discharge power of 1700 equals 1530W on my P1 meter
- charging 1940W equals 2140W on my P1
This is very relevant when you are looking to the integrals of both numbers. It will seem like the Sessy has no energy losses at all.

**Comment by StevenLooman** [comment]
Is there any news on this?

**Comment by PimDoos** [comment]
I spoke to the Sessy team recently, energy sensors are on their backlog, but is not their priority yet (current focus is stability and core features). I do expect it in the coming weeks/months.

**Comment by PimDoos** [comment]
Updated the temporary workaround for now. v0.3.2 adds the separate Charge Power and Discharge Power sensors, so the templates are no longer needed.

**Comment by berendhaan** [comment]
I'm not able to select the charge and discharge entities when configuring the Energy Dashboard, currently running v0.4.0. The unit of measure for both at kW, that is not correct right?

**Comment by PimDoos** [comment]
Hi Berend, you still need to create Riemann Sum Integral helpers to convert the Power sensors in kW to Energy sensors in kWh. The steps above are still applicable

**Comment by newmedia** [comment]
Hi Pim,
My sessy just got installen also (v1.4.0 on the P1/Battery).
I was added the 2 helpers.. but i dont have a sensor called: sensor.sessy_battery_charged or sensor.sessy_battery_discharged.

**Comment by Tazzios** [comment]
Has some one working code use the helpers to calculate the profit per day/month?

**Comment by Sparky699** [comment]
How does this work for multiple sessy's? Adding the helpes x3? How to add them in the energy dashboard then?

**Comment by FabianZoon** [comment]
Tip: The helpers are only triggered when something is happening. Only then they will change from the Unknown value and will they be visible to be picked by the configure the battery in the energy dashboard. You need first do some charging/uncharging before you can use them.

**Comment by Tazzios** [comment]
> Has some one working code use the helpers to calculate the profit per day/month?

For the profit calculation, I have created the following:
```
template:
  - sensor:
      - name: Sessy_EUR_uur
        unit_of_measurement: EUR
        state:  >
          {% set laden = states.sensor.sessy_XXXX_power.state | float(0) %}
          {% set price = states.sensor.electricity_price.state | float %}
          {{ ((laden/1000) * price) }}
```
Create a Reimann sensor using the sensor, trapezoidal rule (if i remember correct).

Create the utility meters that you want:
```
utility_meter:
  sessy_eur_dag:
    name: Sessy_EUR_dag
    source: sensor.sessy_eur_reimann
    cycle: daily
    net_consumption: true 
    
  sessy_eur_maand:
    name: Sessy_EUR_maand
    source: sensor.sessy_eur_reimann
    cycle: monthly
    net_consumption: true 
```
